MLL logo as default Table loading indicator
mll-lab/react-components pull request #116
Opened 2022-01-03 14:28 UTC by mic-web

2022-01-03 15:57 UTC, spawnia requested changes

2022-01-03 15:57 UTC, spawnia commented on src/Spinner/MllSpinnerIcon.tsx
> +const MllSpinnerIconComponent: IconComponentProps['component'] = () =>
Can be inlined

2022-01-03 15:57 UTC, spawnia commented on src/Table/index.tsx
> +function loadingProps<T>({ loading }: TableProps<T>): TableProps<T>['loading'] {
Less typing required when inlined, reuse is unlikely

2022-01-03 15:57 UTC, spawnia commented on src/Table/index.tsx
> +  return {
```suggestion
  }

  return {
```

2022-01-04 08:24 UTC, SimBig commented on src/Table/index.tsx
> -  return <StyledTable rowKey="id" {...props} />;
@mic-web FYI: another possibility is to wrap the styled tabel in a Spin component like I I did it for the `microplate`-component:
`
    <Spin
      spinning={props.loading ?? false}
      indicator={
        <MllSpinnerIcon
          style={{
            width: '2em',
          }}
        />
      }
    >
    `

2022-01-04 08:44 UTC, spawnia approved these changes

2022-01-04 10:43 UTC, merged